"""add net_worth_snapshots table

Revision ID: 54d2212ae901
Revises: 9a4b89218c80
Create Date: 2026-07-23 01:36:45.453462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d2212ae901'
down_revision: Union[str, Sequence[str], None] = '9a4b89218c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_snapshot_date')
    )
    op.create_index(op.f('ix_net_worth_snapshots_user_id'), 'net_worth_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_net_worth_snapshots_user_id'), table_name='net_worth_snapshots')
    op.drop_table('net_worth_snapshots')
    # ### end Alembic commands ###
