"""add bank_connections table and link accounts to it

Revision ID: bd8bf3281cbe
Revises: bda4802628c7
Create Date: 2026-09-18 14:47:03.675989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8bf3281cbe'
down_revision: Union[str, Sequence[str], None] = 'bda4802628c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=255), nullable=False),
    sa.Column('encrypted_access_token', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_item_id')
    )
    op.create_index(op.f('ix_bank_connections_user_id'), 'bank_connections', ['user_id'], unique=False)
    op.add_column('accounts', sa.Column('bank_connection_id', sa.UUID(), nullable=True))
    op.add_column('accounts', sa.Column('plaid_account_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'accounts', ['plaid_account_id'])
    op.create_foreign_key(None, 'accounts', 'bank_connections', ['bank_connection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'plaid_account_id')
    op.drop_column('accounts', 'bank_connection_id')
    op.drop_index(op.f('ix_bank_connections_user_id'), table_name='bank_connections')
    op.drop_table('bank_connections')
    # ### end Alembic commands ###
