"""add daily_summaries table and daily_summary_enabled preference

Revision ID: bda4802628c7
Revises: 1aa3de2ff390
Create Date: 2026-09-17 23:02:16.674597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda4802628c7'
down_revision: Union[str, Sequence[str], None] = '1aa3de2ff390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('by_category', sa.JSON(), nullable=False),
    sa.Column('daily_average', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percent_vs_average', sa.Float(), nullable=True),
    sa.Column('unusual_transactions', sa.JSON(), nullable=False),
    sa.Column('budget_warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_summary_date')
    )
    op.create_index(op.f('ix_daily_summaries_user_id'), 'daily_summaries', ['user_id'], unique=False)
    op.add_column('users', sa.Column('daily_summary_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_summary_enabled')
    op.drop_index(op.f('ix_daily_summaries_user_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
